export const STATIC_PROJECTS = [
  {
    id: 1,
    title: "Portfolio Website",
    description: "A modern, responsive portfolio website built with Next.js, showcasing projects and skills with optimized performance.",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    github_url: "https://github.com",
    live_url: "https://portfolio.example.com",
    featured: true,
    image_url: "/placeholder.jpg",
  },
  {
    id: 2,
    title: "Full-Stack E-Commerce Platform",
    description: "A complete e-commerce solution with user authentication, product management, and payment integration.",
    technologies: ["Python", "Django", "React", "PostgreSQL", "Stripe"],
    github_url: "https://github.com",
    live_url: "https://ecommerce.example.com",
    featured: true,
    image_url: "/placeholder.jpg",
  },
  {
    id: 3,
    title: "Data Analytics Dashboard",
    description: "Interactive dashboard for visualizing and analyzing business metrics with real-time data updates.",
    technologies: ["Python", "Tableau", "Power BI", "SQL"],
    github_url: "https://github.com",
    live_url: "https://dashboard.example.com",
    featured: false,
    image_url: "/placeholder.jpg",
  },
  {
    id: 4,
    title: "Mobile Task Manager",
    description: "A feature-rich task management mobile app with offline support and cloud synchronization.",
    technologies: ["React Native", "Firebase", "TypeScript"],
    github_url: "https://github.com",
    live_url: "https://taskmanager.example.com",
    featured: false,
    image_url: "/placeholder.jpg",
  },
]
